# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
- development

pr:
- master
- develop

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  tagshelfRegistry: 'docker.tagshelf.io'
  imageName: 'tagshelfsrl/duckling'

jobs:
  - job: build
    steps:
      - script: docker build -f Dockerfile -t $(imageName) .
        displayName: 'docker build'
  - job: tagImage
    steps:
      - ${{ if eq(build.SourceBranchName, 'master') }}:
        - script: docker tag $(imageName) "$(tagshelfRegistry)/$(imageName):latest"
          displayName: 'docker tag master as latest'
      - ${{ if eq(build.SourceBranchName, 'development') }}:
        - script: docker tag $(imageName) "$(tagshelfRegistry)/$(imageName):$(build.SourceBranchName)"
          displayName: 'docker tag development'
      - script: docker tag $(imageName) "$(tagshelfRegistry)/$(imageName):$(build.SourceBranchName)_$(build.SourceVersion)"
        displayName: 'docker tag '